#!/bin/fish

set lock_effect
set wal_effect --blur 1

source $HOME/.cache/wal/colors-fish.sh

multilockscreen -u $wallpaper $wal_effect $lock_effect --fx (echo $wal_effect | sed 's/ .*/,/; s/--//')(echo $lock_effect | sed 's/ .*//; s/--//')

switch (echo $wal_effect | sed 's/ .*//;')
	case ''
		feh --bg-fill "$HOME/.cache/multilock/current/wall_resize.png"
	case --dim
		feh --bg-fill "$HOME/.cache/multilock/current/wall_dim.png"
	case --blur
		feh --bg-fill "$HOME/.cache/multilock/current/wall_blur.png"
	case --dimblur
		feh --bg-fill "$HOME/.cache/multilock/current/wall_dimblur.png"
	case --pixel
		feh --bg-fill "$HOME/.cache/multilock/current/wall_pixel.png"
	case --dimpixel
		feh --bg-fill "$HOME/.cache/multilock/current/wall_dimpixel.png"
end

pywalfox update &
sudo make -C /home/kyle/packages/dwm clean install
sudo make -C /home/kyle/packages/dmenu clean install 
killall dwm

echo "#!/bin/fish"\n"multilockscreen -l (echo $lock_effect | sed 's/ .*//; s/--//') --off 10s" > $HOME/scripts/lock.sh
