#!/bin/sh
wal -R -n
xmodmap .config/xmodmap &
killall xcape
xcape -e 'Mode_switch=Escape' &
picom & 
$HOME/.fehbg
/home/kyle/scripts/startdunst &
/usr/lib/kdeconnectd &
xss-lock -- lock.sh &
autorandr -c
